# Use official Nginx Alpine image for lightweight production deployment
FROM nginx:alpine

# Set maintainer label for image identification
LABEL maintainer="Student Management Team"
LABEL description="Angular frontend for Student Management System"
LABEL version="1.0"

# Copy built Angular application to Nginx serve directory
# Source: dist/etudiant-frontend/browser (generated by Angular CLI)
COPY dist/etudiant-frontend/browser /usr/share/nginx/html

# Copy custom Nginx configuration for SPA routing and API proxy
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80 for HTTP traffic
EXPOSE 80

# Add health check for container monitoring
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
    CMD curl -f http://localhost/ || exit 1